name: Create prerelease

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-prerelease'

permissions:
  contents: write

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
  create-prerelease:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: ./configs/cliff.toml
          args: --verbose
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: atmosphere-artifacts
          path: "./"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "atmosphere-*.zip,fusee.bin"
          prerelease: true
          name: "Evaron-Atmosph√®re ${{ github.ref_name }}"
          bodyFile: "CHANGELOG.md"
